title: Jared Sorrentino # your name (or website title) here
logo: "/profile.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
As a passionate aspiring data analyst, I bring a unique blend of analytical rigor, creative problem-solving, and a relentless drive to uncover actionable insights that transform data into impactful decisions.
<br><br>
  <a href="www.linkedin.com/in/jared-sorrentino-b49407b4">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
